### ISSUE TITLE
Increase RTD reading

### ISSUE THREAD

**Issue by Fabien-Roots** [drhaney/pt100rtd#1]
Hi,
I wont to know if it possible to increase the RTD Reading to the MAX31865.cpp, to have better resolution.

Actually the code give : rtd: 0x2015, ohms: 107.77

For my, instrumentation i needed rtd: 0x2015, ohms: 107.77**# 7**

Sorry i'm not a expert with the MAX31865, and i need help.

Thanks in advance

**Comment by drhaney** [comment]
The MAX31865 is a 15-bit device that confers 0.013 ohms resolution using a 430 ohm reference resistor.  That's all you get.  It doesn't make sense to create a resolution beyond that of the measuring chip. 

However, you can _**print**_ at any decimal resolution you like.  See **_line 109_** in [pt100rtd/examples/pt100_temperature/](https://github.com/drhaney/pt100rtd/tree/master/examples/pt100_temperature) where it says

>	Serial.print(", ohms: ") ; Serial.println(ohms,**_2_**) ;

Change the **_2_** to any number between 1 and 15, the maximum decimal point resolution of 'double' type real numbers in C++.  The full 15 decimal points is contained the the variable **_ohms_**.

**Comment by Fabien-Roots** [comment]
Thanks for the answer, i already make this (ohms,3) but the value have a résolution of 0,02°C, i cant have a better resolution, to have précise variation ( for example : 12.0312, 12.0311, 12.0313) i have only 12.030, 12.050, 12.010 ... 
Did you think that is possible to increase the RTD read for the MAX31865, because this value it's enought accurate to have a résolution of 0.001°C.
Best regards
