### ISSUE TITLE
830 C degree reading

### ISSUE THREAD

**Issue by pdrobek** [drhaney/pt100rtd#3]
Hi

Please let me know if you know ansewer. I use your librarty in my sketch and shows near 830 C degree reading, do you know where i could search for problem?

**Comment by drhaney** [comment]
Is your RTD a Pt100?  This does not work with the 1000 ohm Pt1000.

**Comment by pdrobek** [comment]
All are pt100 (sensor and board)

i realised that i power-on board with pt100 later than esp8266 or arduino
it shows correct values.

Dunno what i made wrong.

Also i made discovery, after power-on whole thing up (incorrect values)
than disconnect vin or gnd from max31865 board and connect again in the
same places as before i got correct values.

Can you tell me what is going on?

wt., 21 sty 2020, 13:41 użytkownik drhaney <notifications@github.com>
napisał:
